import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { 
  LogOut, 
  RefreshCw, 
  Send, 
  Database, 
  FileText, 
  AlertTriangle,
  CheckCircle2,
  Activity,
  Server
} from 'lucide-react';

interface DashboardStats {
  tenant_id: string;
  knowledge_base: {
    active_documents: number;
    archived_documents: number;
  };
  erp_sync: {
    source_system: string;
    total_tracked: number;
    active_synced: number;
    deleted: number;
    failed: number;
    last_synced_at: string | null;
    department_counts: Record<string, number>;
  };
  escalations: {
    open_cases: number;
    resolved_cases: number;
  };
  recent_audit_logs: any[];
}

export default function Dashboard() {
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [syncing, setSyncing] = useState(false);
  const [webhookData, setWebhookData] = useState({
    external_record_id: 'ERP-999',
    action: 'update',
    title: 'Q4 Review Guidelines'
  });
  const [webhookStatus, setWebhookStatus] = useState('');
  
  const navigate = useNavigate();
  const token = localStorage.getItem('token');
  const tenantId = localStorage.getItem('tenant_id');

  const fetchDashboard = async () => {
    try {
      const res = await axios.get(`http://localhost:8000/tenants/${tenantId}/dashboard`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setStats(res.data);
    } catch (err) {
      console.error(err);
      if (err.response?.status === 401) handleLogout();
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDashboard();
  }, []);

  const handleLogout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('tenant_id');
    navigate('/login');
  };

  const triggerSync = async () => {
    setSyncing(true);
    try {
      await axios.post(`http://localhost:8000/tenants/${tenantId}/erp/sync`, {}, {
        headers: { Authorization: `Bearer ${token}` }
      });
      await fetchDashboard();
    } catch (err) {
      console.error(err);
      alert('Sync failed or unauthorized.');
    } finally {
      setSyncing(false);
    }
  };

  const triggerWebhook = async (e: React.FormEvent) => {
    e.preventDefault();
    setWebhookStatus('Sending...');
    try {
      // In a real app, the signature is generated by the sender.
      // Here we just send the payload and simulate the signature generation in the test/demo env.
      await axios.post(`http://localhost:8000/erp/webhook`, {
        tenant_id: tenantId,
        source_system: 'mock_erp',
        events: [
          {
            external_record_id: webhookData.external_record_id,
            action: webhookData.action,
            entity_type: 'document',
            payload: {
              title: webhookData.title,
              department: 'Finance'
            },
            timestamp: new Date().toISOString()
          }
        ]
      }, {
        headers: { 
          // For simulation, the API is configured to bypass or check a dummy signature in test mode.
          // Since it's a mock connector, we pass a dummy signature or run in test mode.
          'X-ERP-Signature': 'simulated_signature'
        }
      });
      setWebhookStatus('Success!');
      setTimeout(() => setWebhookStatus(''), 3000);
      fetchDashboard();
    } catch (err) {
      console.error(err);
      setWebhookStatus('Failed (unauthorized)');
    }
  };

  if (loading) {
    return <div className="min-h-screen flex items-center justify-center"><RefreshCw className="w-8 h-8 animate-spin text-primary" /></div>;
  }

  return (
    <div className="min-h-screen p-8 max-w-7xl mx-auto">
      <header className="flex justify-between items-center mb-10">
        <div className="flex items-center gap-3">
          <div className="bg-primary/20 p-2 rounded-xl border border-primary/30">
            <Database className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h1 className="text-2xl font-bold">EKA Control Center</h1>
            <p className="text-sm text-textMuted">Tenant: {tenantId}</p>
          </div>
        </div>
        <button onClick={handleLogout} className="flex items-center gap-2 text-textMuted hover:text-white transition-colors">
          <LogOut className="w-4 h-4" /> Sign Out
        </button>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {/* Knowledge Base Card */}
        <div className="glass-panel p-6">
          <div className="flex items-center gap-3 mb-4 text-textMuted">
            <FileText className="w-5 h-5 text-blue-400" />
            <h2 className="font-semibold text-white">Knowledge Base</h2>
          </div>
          <div className="flex justify-between items-end">
            <div>
              <p className="text-3xl font-bold">{stats?.knowledge_base.active_documents}</p>
              <p className="text-sm text-textMuted">Active Documents</p>
            </div>
            <div className="text-right">
              <p className="text-xl font-semibold text-textMuted">{stats?.knowledge_base.archived_documents}</p>
              <p className="text-xs text-textMuted">Archived</p>
            </div>
          </div>
        </div>

        {/* Escalations Card */}
        <div className="glass-panel p-6">
          <div className="flex items-center gap-3 mb-4 text-textMuted">
            <AlertTriangle className="w-5 h-5 text-yellow-400" />
            <h2 className="font-semibold text-white">Escalations</h2>
          </div>
          <div className="flex justify-between items-end">
            <div>
              <p className="text-3xl font-bold text-yellow-400">{stats?.escalations.open_cases}</p>
              <p className="text-sm text-textMuted">Open Cases</p>
            </div>
            <div className="text-right">
              <p className="text-xl font-semibold text-textMuted">{stats?.escalations.resolved_cases}</p>
              <p className="text-xs text-textMuted">Resolved</p>
            </div>
          </div>
        </div>

        {/* ERP Sync Card */}
        <div className="glass-panel p-6">
          <div className="flex items-center gap-3 mb-4 text-textMuted">
            <Server className="w-5 h-5 text-emerald-400" />
            <h2 className="font-semibold text-white">ERP Synchronization</h2>
          </div>
          <div className="flex justify-between items-end">
            <div>
              <p className="text-3xl font-bold text-emerald-400">{stats?.erp_sync.active_synced}</p>
              <p className="text-sm text-textMuted">Synced Records</p>
            </div>
            <div className="text-right">
              <p className="text-xl font-semibold text-textMuted">{stats?.erp_sync.failed}</p>
              <p className="text-xs text-textMuted">Failures</p>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Actions Panel */}
        <div className="space-y-8">
          <div className="glass-panel p-6">
            <h2 className="text-lg font-semibold mb-2 flex items-center gap-2">
              <RefreshCw className="w-5 h-5 text-primary" /> Batch Synchronization
            </h2>
            <p className="text-sm text-textMuted mb-6">
              Manually trigger the background reconciliation job. This will pull all changes from the Mock ERP since the last sync timestamp.
            </p>
            <button 
              onClick={triggerSync} 
              disabled={syncing}
              className="btn-primary w-full flex justify-center items-center gap-2"
            >
              {syncing ? <RefreshCw className="w-5 h-5 animate-spin" /> : <Database className="w-5 h-5" />}
              {syncing ? 'Synchronizing with ERP...' : 'Trigger Full Sync'}
            </button>
            <p className="text-xs text-textMuted mt-4 text-center">
              Last synced: {stats?.erp_sync.last_synced_at ? new Date(stats.erp_sync.last_synced_at).toLocaleString() : 'Never'}
            </p>
          </div>

          <div className="glass-panel p-6">
            <h2 className="text-lg font-semibold mb-2 flex items-center gap-2">
              <Activity className="w-5 h-5 text-accent" /> Webhook Simulator
            </h2>
            <p className="text-sm text-textMuted mb-6">
              Simulate an incoming HTTP webhook from the external ERP system.
            </p>
            
            <form onSubmit={triggerWebhook} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-textMuted mb-1">Record ID</label>
                  <input 
                    type="text" 
                    value={webhookData.external_record_id}
                    onChange={e => setWebhookData({...webhookData, external_record_id: e.target.value})}
                    className="input-field text-sm" 
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-textMuted mb-1">Action</label>
                  <select 
                    value={webhookData.action}
                    onChange={e => setWebhookData({...webhookData, action: e.target.value})}
                    className="input-field text-sm"
                  >
                    <option value="create">Create</option>
                    <option value="update">Update</option>
                    <option value="delete">Delete</option>
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-xs font-medium text-textMuted mb-1">Document Title</label>
                <input 
                  type="text" 
                  value={webhookData.title}
                  onChange={e => setWebhookData({...webhookData, title: e.target.value})}
                  className="input-field text-sm" 
                />
              </div>
              <div className="flex items-center gap-4">
                <button type="submit" className="btn-primary flex-1 flex justify-center items-center gap-2 bg-accent hover:bg-accent/80">
                  <Send className="w-4 h-4" /> Fire Webhook
                </button>
                {webhookStatus && (
                  <span className={`text-sm ${webhookStatus.includes('Fail') ? 'text-red-400' : 'text-emerald-400'}`}>
                    {webhookStatus}
                  </span>
                )}
              </div>
            </form>
          </div>
        </div>

        {/* Audit Logs */}
        <div className="glass-panel p-6 h-full flex flex-col">
          <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-blue-400" /> Recent Audit Activity
          </h2>
          <div className="flex-1 overflow-auto pr-2 space-y-3">
            {stats?.recent_audit_logs?.length === 0 ? (
              <p className="text-sm text-textMuted text-center mt-10">No recent activity.</p>
            ) : (
              stats?.recent_audit_logs.map(log => (
                <div key={log.id} className="bg-background/50 border border-border/50 rounded-lg p-3 text-sm">
                  <div className="flex justify-between items-start mb-1">
                    <span className="font-semibold text-primary">{log.action}</span>
                    <span className="text-xs text-textMuted">{new Date(log.timestamp).toLocaleTimeString()}</span>
                  </div>
                  <div className="text-xs text-textMuted">
                    {log.document_id && <p>Doc: <span className="font-mono text-white/70">{log.document_id}</span></p>}
                    {log.user_id && <p>User: <span className="font-mono text-white/70">{log.user_id}</span></p>}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
